version: 0.0
os: linux
files:
- source: /
  destination: /home/ec2-user
hooks:
  AfterInstall:
<<<<<<< HEAD
    - location: fix_previleges.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_server.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: stop_server.sh
      timeout: 20
      runas: ec2-user
=======
  - location: fix_previleges.sh
    timeout: 300
    runas: root
  ApplicationStart:
  - location: start_server.sh
    timeout: 300
    runas: root
  ApplicationStop:
  - location: stop_server.sh
    timeout: 300
    runas: root
>>>>>>> eb24b0be16b55b16d7ef4706f10eccc25302b458
